from __future__ import annotations

from src.core.modules.project_management.contracts.financial_sources import (
    FinancialPostingPurpose,
    FinancialSourceModule,
    FinancialSourceType,
)
from src.core.modules.project_management.domain.financials.cost_entry import (
    ProjectCostEntry,
    ProjectCostEntryKind,
    ProjectCostEntryStatus,
)
from src.core.modules.project_management.infrastructure.persistence.orm.cost_entry import (
    ProjectCostEntryORM,
)


def cost_entry_to_orm(entry: ProjectCostEntry) -> ProjectCostEntryORM:
    return ProjectCostEntryORM(
        id=entry.id,
        tenant_id=entry.tenant_id,
        organization_id=entry.organization_id,
        project_id=entry.project_id,
        description=entry.description,
        entry_kind=entry.entry_kind.value,
        status=entry.status.value,
        amount=entry.amount,
        currency_code=entry.currency_code,
        base_amount=entry.base_amount,
        base_currency_code=entry.base_currency_code,
        exchange_rate=entry.exchange_rate,
        exchange_rate_date=entry.exchange_rate_date,
        exchange_rate_source=entry.exchange_rate_source,
        exchange_rate_captured_at=entry.exchange_rate_captured_at,
        transaction_date=entry.transaction_date,
        posting_date=entry.posting_date,
        financial_period_id=entry.financial_period_id,
        cost_code_id=entry.cost_code_id,
        task_id=entry.task_id,
        resource_id=entry.resource_id,
        source_module=entry.source_module.value,
        source_type=entry.source_type.value,
        source_id=entry.source_id,
        source_line_id=entry.source_line_id,
        source_revision=entry.source_revision,
        source_content_hash=entry.source_content_hash,
        posting_purpose=entry.posting_purpose.value,
        idempotency_key=entry.idempotency_key,
        reverses_entry_id=entry.reverses_entry_id,
        reversed_by_entry_id=entry.reversed_by_entry_id,
        version=entry.row_version,
        created_by=entry.created_by,
        created_at=entry.created_at,
        updated_by=entry.updated_by,
        updated_at=entry.updated_at,
        submitted_by=entry.submitted_by,
        submitted_at=entry.submitted_at,
        approved_by=entry.approved_by,
        approved_at=entry.approved_at,
        rejected_by=entry.rejected_by,
        rejected_at=entry.rejected_at,
        rejection_notes=entry.rejection_notes,
        posted_by=entry.posted_by,
        posted_at=entry.posted_at,
        reversed_by=entry.reversed_by,
        reversed_at=entry.reversed_at,
    )


def cost_entry_from_orm(row: ProjectCostEntryORM) -> ProjectCostEntry:
    return ProjectCostEntry(
        id=row.id,
        tenant_id=row.tenant_id,
        organization_id=row.organization_id,
        project_id=row.project_id,
        description=row.description,
        entry_kind=ProjectCostEntryKind(row.entry_kind),
        status=ProjectCostEntryStatus(row.status),
        amount=row.amount,
        currency_code=row.currency_code,
        base_amount=row.base_amount,
        base_currency_code=row.base_currency_code,
        exchange_rate=row.exchange_rate,
        exchange_rate_date=row.exchange_rate_date,
        exchange_rate_source=row.exchange_rate_source,
        exchange_rate_captured_at=row.exchange_rate_captured_at,
        transaction_date=row.transaction_date,
        posting_date=row.posting_date,
        financial_period_id=row.financial_period_id,
        cost_code_id=row.cost_code_id,
        task_id=row.task_id,
        resource_id=row.resource_id,
        source_module=FinancialSourceModule(row.source_module),
        source_type=FinancialSourceType(row.source_type),
        source_id=row.source_id,
        source_line_id=row.source_line_id,
        source_revision=row.source_revision,
        source_content_hash=row.source_content_hash,
        posting_purpose=FinancialPostingPurpose(row.posting_purpose),
        idempotency_key=row.idempotency_key,
        reverses_entry_id=row.reverses_entry_id,
        reversed_by_entry_id=row.reversed_by_entry_id,
        row_version=row.version,
        created_by=row.created_by,
        created_at=row.created_at,
        updated_by=row.updated_by,
        updated_at=row.updated_at,
        submitted_by=row.submitted_by,
        submitted_at=row.submitted_at,
        approved_by=row.approved_by,
        approved_at=row.approved_at,
        rejected_by=row.rejected_by,
        rejected_at=row.rejected_at,
        rejection_notes=row.rejection_notes,
        posted_by=row.posted_by,
        posted_at=row.posted_at,
        reversed_by=row.reversed_by,
        reversed_at=row.reversed_at,
    )


__all__ = ["cost_entry_from_orm", "cost_entry_to_orm"]
