"""Maintenance QML view models."""

from src.ui_qml.modules.maintenance.view_models.dashboard import (
    MaintenanceDashboardBacklogRowViewModel,
    MaintenanceDashboardOverviewViewModel,
    MaintenanceDashboardRecurringRowViewModel,
    MaintenanceDashboardRootCauseRowViewModel,
    MaintenanceDashboardWorkspaceViewModel,
    MaintenanceMetricViewModel,
    MaintenanceOptionViewModel,
)
from src.ui_qml.modules.maintenance.view_models.planner import (
    MaintenancePlannerMaterialRiskRowViewModel,
    MaintenancePlannerMetricViewModel,
    MaintenancePlannerOptionViewModel,
    MaintenancePlannerOverviewViewModel,
    MaintenancePlannerPreventiveRowViewModel,
    MaintenancePlannerRecurringRowViewModel,
    MaintenancePlannerRequestRowViewModel,
    MaintenancePlannerWorkOrderRowViewModel,
    MaintenancePlannerWorkspaceViewModel,
)
from src.ui_qml.modules.maintenance.view_models.reliability import (
    MaintenanceFailureSymptomOptionViewModel,
    MaintenanceReliabilityInsightRowViewModel,
    MaintenanceReliabilityMetricViewModel,
    MaintenanceReliabilityOptionViewModel,
    MaintenanceReliabilityOverviewViewModel,
    MaintenanceReliabilityRecurringRowViewModel,
    MaintenanceReliabilitySuggestionRowViewModel,
    MaintenanceReliabilityWorkspaceViewModel,
)
from src.ui_qml.modules.maintenance.view_models.work_requests import (
    MaintenanceWorkRequestDetailFieldViewModel,
    MaintenanceWorkRequestDetailViewModel,
    MaintenanceWorkRequestMetricViewModel,
    MaintenanceWorkRequestOptionViewModel,
    MaintenanceWorkRequestOverviewViewModel,
    MaintenanceWorkRequestRecordViewModel,
    MaintenanceWorkRequestsWorkspaceViewModel,
)
from src.ui_qml.modules.maintenance.view_models.work_orders import (
    MaintenanceWorkOrderDetailFieldViewModel,
    MaintenanceWorkOrderDetailViewModel,
    MaintenanceWorkOrderMetricViewModel,
    MaintenanceWorkOrderOptionViewModel,
    MaintenanceWorkOrderOverviewViewModel,
    MaintenanceWorkOrderRecordViewModel,
    MaintenanceWorkOrdersWorkspaceViewModel,
)
from src.ui_qml.modules.maintenance.view_models.workspace import (
    MaintenanceWorkspaceViewModel,
)

__all__ = [
    "MaintenanceDashboardBacklogRowViewModel",
    "MaintenanceDashboardOverviewViewModel",
    "MaintenanceDashboardRecurringRowViewModel",
    "MaintenanceDashboardRootCauseRowViewModel",
    "MaintenanceDashboardWorkspaceViewModel",
    "MaintenanceFailureSymptomOptionViewModel",
    "MaintenanceMetricViewModel",
    "MaintenanceOptionViewModel",
    "MaintenancePlannerMaterialRiskRowViewModel",
    "MaintenancePlannerMetricViewModel",
    "MaintenancePlannerOptionViewModel",
    "MaintenancePlannerOverviewViewModel",
    "MaintenancePlannerPreventiveRowViewModel",
    "MaintenancePlannerRecurringRowViewModel",
    "MaintenancePlannerRequestRowViewModel",
    "MaintenancePlannerWorkOrderRowViewModel",
    "MaintenancePlannerWorkspaceViewModel",
    "MaintenanceReliabilityInsightRowViewModel",
    "MaintenanceReliabilityMetricViewModel",
    "MaintenanceReliabilityOptionViewModel",
    "MaintenanceReliabilityOverviewViewModel",
    "MaintenanceReliabilityRecurringRowViewModel",
    "MaintenanceReliabilitySuggestionRowViewModel",
    "MaintenanceReliabilityWorkspaceViewModel",
    "MaintenanceWorkRequestDetailFieldViewModel",
    "MaintenanceWorkRequestDetailViewModel",
    "MaintenanceWorkRequestMetricViewModel",
    "MaintenanceWorkRequestOptionViewModel",
    "MaintenanceWorkRequestOverviewViewModel",
    "MaintenanceWorkRequestRecordViewModel",
    "MaintenanceWorkRequestsWorkspaceViewModel",
    "MaintenanceWorkOrderDetailFieldViewModel",
    "MaintenanceWorkOrderDetailViewModel",
    "MaintenanceWorkOrderMetricViewModel",
    "MaintenanceWorkOrderOptionViewModel",
    "MaintenanceWorkOrderOverviewViewModel",
    "MaintenanceWorkOrderRecordViewModel",
    "MaintenanceWorkOrdersWorkspaceViewModel",
    "MaintenanceWorkspaceViewModel",
]
