"""baseline

Revision ID: ef8d1d37eabf
Revises: 
Create Date: 2025-12-23 16:10:18.774665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8d1d37eabf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'ON_HOLD', 'COMPLETED', name='projectstatus'), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_contact', sa.String(), nullable=True),
    sa.Column('planned_budget', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cost_type', sa.Enum('LABOR', 'MATERIAL', 'OVERHEAD', 'EQUIPMENT', 'CONTINGENCY', 'SUBCONTRACT', 'OTHER', name='costtype'), nullable=False),
    sa.Column('currency_code', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('working_calendars',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('working_days', sa.String(), nullable=False),
    sa.Column('hours_per_day', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidays',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calendar_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['working_calendars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_holiday_calendar_date', 'holidays', ['calendar_id', 'date'], unique=False)
    op.create_table('project_baselines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_baseline_created', 'project_baselines', ['created_at'], unique=False)
    op.create_index('idx_baseline_project', 'project_baselines', ['project_id'], unique=False)
    op.create_table('project_resources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('currency_code', sa.String(length=8), nullable=True),
    sa.Column('planned_hours', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_resource_project', 'project_resources', ['project_id'], unique=False)
    op.create_index('idx_project_resource_resource', 'project_resources', ['resource_id'], unique=False)
    op.create_index('ux_project_resource_project_resource', 'project_resources', ['project_id', 'resource_id'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'BLOCKED', 'DONE', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('percent_complete', sa.Float(), nullable=False),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_project_id', 'tasks', ['project_id'], unique=False)
    op.create_table('baseline_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('baseline_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('baseline_start', sa.Date(), nullable=True),
    sa.Column('baseline_finish', sa.Date(), nullable=True),
    sa.Column('baseline_duration_days', sa.Integer(), nullable=False),
    sa.Column('baseline_planned_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['project_baselines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_baseline_task_baseline', 'baseline_tasks', ['baseline_id'], unique=False)
    op.create_index('idx_baseline_task_task', 'baseline_tasks', ['task_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calendar_start_end', 'calendar_events', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_clandar_project', 'calendar_events', ['project_id'], unique=False)
    op.create_table('cost_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('cost_type', sa.String(), nullable=False),
    sa.Column('currency_code', sa.String(length=8), nullable=True),
    sa.Column('planned_amount', sa.Float(), nullable=False),
    sa.Column('committed_amount', sa.Float(), nullable=False),
    sa.Column('actual_amount', sa.Float(), nullable=False),
    sa.Column('incurred_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_costs_project', 'cost_items', ['project_id'], unique=False)
    op.create_index('idx_costs_task', 'cost_items', ['task_id'], unique=False)
    op.create_index('idx_costs_type', 'cost_items', ['cost_type'], unique=False)
    op.create_table('task_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('allocation_percent', sa.Float(), nullable=False),
    sa.Column('hours_logged', sa.Float(), nullable=False),
    sa.Column('project_resource_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_resource_id'], ['project_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_assignments_project_resource', 'task_assignments', ['project_resource_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('predecessor_task_id', sa.String(), nullable=False),
    sa.Column('successor_task_id', sa.String(), nullable=False),
    sa.Column('dependency_type', sa.Enum('FINISH_TO_START', 'FINISH_TO_FINISH', 'START_TO_START', 'START_TO_FINISH', name='dependencytype'), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dep_predecessor', 'task_dependencies', ['predecessor_task_id'], unique=False)
    op.create_index('idx_dep_successor', 'task_dependencies', ['successor_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dep_successor', table_name='task_dependencies')
    op.drop_index('idx_dep_predecessor', table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index('idx_task_assignments_project_resource', table_name='task_assignments')
    op.drop_table('task_assignments')
    op.drop_index('idx_costs_type', table_name='cost_items')
    op.drop_index('idx_costs_task', table_name='cost_items')
    op.drop_index('idx_costs_project', table_name='cost_items')
    op.drop_table('cost_items')
    op.drop_index('idx_clandar_project', table_name='calendar_events')
    op.drop_index('idx_calendar_start_end', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index('idx_baseline_task_task', table_name='baseline_tasks')
    op.drop_index('idx_baseline_task_baseline', table_name='baseline_tasks')
    op.drop_table('baseline_tasks')
    op.drop_index('idx_tasks_project_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ux_project_resource_project_resource', table_name='project_resources')
    op.drop_index('idx_project_resource_resource', table_name='project_resources')
    op.drop_index('idx_project_resource_project', table_name='project_resources')
    op.drop_table('project_resources')
    op.drop_index('idx_baseline_project', table_name='project_baselines')
    op.drop_index('idx_baseline_created', table_name='project_baselines')
    op.drop_table('project_baselines')
    op.drop_index('idx_holiday_calendar_date', table_name='holidays')
    op.drop_table('holidays')
    op.drop_table('working_calendars')
    op.drop_table('resources')
    op.drop_table('projects')
    # ### end Alembic commands ###
