from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]

PATH_REWRITE_EXACT = {
    "core/domain/__init__.py": "core/modules/project_management/domain/__init__.py",
    "core/interfaces.py": "src/core/platform/common/interfaces.py",
    "core/exceptions.py": "src/core/platform/common/exceptions.py",
    "core/platform/common/__init__.py": "src/core/platform/common/__init__.py",
    "core/platform/common/exceptions.py": "src/core/platform/common/exceptions.py",
    "core/platform/common/ids.py": "src/core/platform/common/ids.py",
    "core/platform/common/interfaces.py": "src/core/platform/common/interfaces.py",
    "core/platform/common/runtime_access.py": "src/core/platform/common/runtime_access.py",
    "core/platform/common/service_base.py": "src/core/platform/common/service_base.py",
    "core/platform/data_exchange/__init__.py": "src/core/platform/data_exchange/__init__.py",
    "core/platform/data_exchange/service.py": "src/core/platform/data_exchange/service.py",
    "ui/platform/settings/__init__.py": "src/ui/platform/settings/__init__.py",
    "ui/platform/settings/main_window_store.py": "src/ui/platform/settings/main_window_store.py",
    "ui/platform/control/__init__.py": "src/ui/platform/workspaces/control/__init__.py",
    "ui/platform/control/approvals/__init__.py": "src/ui/platform/workspaces/control/approvals/__init__.py",
    "ui/platform/control/approvals/presentation.py": "src/ui/platform/workspaces/control/approvals/presentation.py",
    "ui/platform/control/approvals/queue.py": "src/ui/platform/workspaces/control/approvals/queue.py",
    "ui/platform/control/approvals/tab.py": "src/ui/platform/workspaces/control/approvals/tab.py",
    "ui/platform/control/audit/__init__.py": "src/ui/platform/workspaces/control/audit/__init__.py",
    "ui/platform/control/audit/tab.py": "src/ui/platform/workspaces/control/audit/tab.py",
    "ui/platform/admin/__init__.py": "src/ui/platform/workspaces/admin/__init__.py",
    "ui/platform/admin/shared_header.py": "src/ui/platform/widgets/admin_header.py",
    "ui/platform/admin/shared_surface.py": "src/ui/platform/widgets/admin_surface.py",
    "ui/platform/admin/access/__init__.py": "src/ui/platform/workspaces/admin/access/__init__.py",
    "ui/platform/admin/access/tab.py": "src/ui/platform/workspaces/admin/access/tab.py",
    "ui/platform/admin/departments/__init__.py": "src/ui/platform/workspaces/admin/departments/__init__.py",
    "ui/platform/admin/departments/dialogs.py": "src/ui/platform/dialogs/admin/departments/dialogs.py",
    "ui/platform/admin/departments/tab.py": "src/ui/platform/workspaces/admin/departments/tab.py",
    "ui/platform/admin/documents/__init__.py": "src/ui/platform/workspaces/admin/documents/__init__.py",
    "ui/platform/admin/documents/dialogs.py": "src/ui/platform/dialogs/admin/documents/dialogs.py",
    "ui/platform/admin/documents/preview.py": "src/ui/platform/widgets/document_preview.py",
    "ui/platform/admin/documents/structure_dialogs.py": "src/ui/platform/dialogs/admin/documents/structure_dialogs.py",
    "ui/platform/admin/documents/tab.py": "src/ui/platform/workspaces/admin/documents/tab.py",
    "ui/platform/admin/documents/viewer_dialogs.py": "src/ui/platform/dialogs/documents/viewer_dialogs.py",
    "ui/platform/admin/employees/__init__.py": "src/ui/platform/workspaces/admin/employees/__init__.py",
    "ui/platform/admin/employees/dialogs.py": "src/ui/platform/dialogs/admin/employees/dialogs.py",
    "ui/platform/admin/employees/tab.py": "src/ui/platform/workspaces/admin/employees/tab.py",
    "ui/platform/admin/modules/__init__.py": "src/ui/platform/workspaces/admin/modules/__init__.py",
    "ui/platform/admin/modules/tab.py": "src/ui/platform/workspaces/admin/modules/tab.py",
    "ui/platform/admin/organizations/__init__.py": "src/ui/platform/workspaces/admin/organizations/__init__.py",
    "ui/platform/admin/organizations/dialogs.py": "src/ui/platform/dialogs/admin/organizations/dialogs.py",
    "ui/platform/admin/organizations/tab.py": "src/ui/platform/workspaces/admin/organizations/tab.py",
    "ui/platform/admin/parties/__init__.py": "src/ui/platform/workspaces/admin/parties/__init__.py",
    "ui/platform/admin/parties/dialogs.py": "src/ui/platform/dialogs/admin/parties/dialogs.py",
    "ui/platform/admin/parties/tab.py": "src/ui/platform/workspaces/admin/parties/tab.py",
    "ui/platform/admin/sites/__init__.py": "src/ui/platform/workspaces/admin/sites/__init__.py",
    "ui/platform/admin/sites/dialogs.py": "src/ui/platform/dialogs/admin/sites/dialogs.py",
    "ui/platform/admin/sites/tab.py": "src/ui/platform/workspaces/admin/sites/tab.py",
    "ui/platform/admin/support/__init__.py": "src/ui/platform/workspaces/admin/support/__init__.py",
    "ui/platform/admin/support/diagnostics_export.py": "src/ui/platform/workspaces/admin/support/diagnostics_export.py",
    "ui/platform/admin/support/diagnostics_flow.py": "src/ui/platform/workspaces/admin/support/diagnostics_flow.py",
    "ui/platform/admin/support/incident_mail.py": "src/ui/platform/workspaces/admin/support/incident_mail.py",
    "ui/platform/admin/support/incident_report.py": "src/ui/platform/workspaces/admin/support/incident_report.py",
    "ui/platform/admin/support/surface.py": "src/ui/platform/workspaces/admin/support/surface.py",
    "ui/platform/admin/support/tab.py": "src/ui/platform/workspaces/admin/support/tab.py",
    "ui/platform/admin/support/telemetry.py": "src/ui/platform/workspaces/admin/support/telemetry.py",
    "ui/platform/admin/support/ui_layout.py": "src/ui/platform/workspaces/admin/support/ui_layout.py",
    "ui/platform/admin/support/update_flow.py": "src/ui/platform/workspaces/admin/support/update_flow.py",
    "ui/platform/admin/users/__init__.py": "src/ui/platform/workspaces/admin/users/__init__.py",
    "ui/platform/admin/users/dialogs.py": "src/ui/platform/dialogs/admin/users/dialogs.py",
    "ui/platform/admin/users/tab.py": "src/ui/platform/workspaces/admin/users/tab.py",
    "ui/platform/shared/__init__.py": "src/ui/shared/__init__.py",
    "ui/platform/shared/async_job.py": "src/ui/shared/dialogs/async_job.py",
    "ui/platform/shared/incident_support.py": "src/ui/shared/dialogs/incident_support.py",
    "ui/platform/shared/auth/__init__.py": "src/ui/shared/dialogs/__init__.py",
    "ui/platform/shared/auth/login_dialog.py": "src/ui/shared/dialogs/login_dialog.py",
    "ui/platform/shared/styles/__init__.py": "src/ui/shared/formatting/__init__.py",
    "ui/platform/shared/styles/formatting.py": "src/ui/shared/formatting/formatting.py",
    "ui/platform/shared/styles/style_utils.py": "src/ui/shared/formatting/style_utils.py",
    "ui/platform/shared/styles/theme.py": "src/ui/shared/formatting/theme.py",
    "ui/platform/shared/styles/theme_refresh.py": "src/ui/shared/formatting/theme_refresh.py",
    "ui/platform/shared/styles/theme_stylesheet.py": "src/ui/shared/formatting/theme_stylesheet.py",
    "ui/platform/shared/styles/theme_tokens.py": "src/ui/shared/formatting/theme_tokens.py",
    "ui/platform/shared/styles/ui_config.py": "src/ui/shared/formatting/ui_config.py",
    "ui/platform/shared/deferred_call.py": "src/ui/shared/models/deferred_call.py",
    "ui/platform/shared/table_model.py": "src/ui/shared/models/table_model.py",
    "ui/platform/shared/undo.py": "src/ui/shared/models/undo.py",
    "ui/platform/shared/worker_services.py": "src/ui/shared/models/worker_services.py",
    "ui/platform/shared/code_generation.py": "src/ui/shared/widgets/code_generation.py",
    "ui/platform/shared/combo.py": "src/ui/shared/widgets/combo.py",
    "ui/platform/shared/guards.py": "src/ui/shared/widgets/guards.py",
    "ui/auth/login_dialog.py": "src/ui/shared/dialogs/login_dialog.py",
    "ui/styles/formatting.py": "src/ui/shared/formatting/formatting.py",
    "ui/styles/style_utils.py": "src/ui/shared/formatting/style_utils.py",
    "ui/styles/theme.py": "src/ui/shared/formatting/theme.py",
    "ui/styles/theme_refresh.py": "src/ui/shared/formatting/theme_refresh.py",
    "ui/styles/theme_stylesheet.py": "src/ui/shared/formatting/theme_stylesheet.py",
    "ui/styles/theme_tokens.py": "src/ui/shared/formatting/theme_tokens.py",
    "ui/styles/ui_config.py": "src/ui/shared/formatting/ui_config.py",
    "ui/shared/async_job.py": "src/ui/shared/dialogs/async_job.py",
    "ui/shared/incident_support.py": "src/ui/shared/dialogs/incident_support.py",
    "ui/shared/deferred_call.py": "src/ui/shared/models/deferred_call.py",
    "ui/shared/table_model.py": "src/ui/shared/models/table_model.py",
    "ui/shared/undo.py": "src/ui/shared/models/undo.py",
    "ui/shared/worker_services.py": "src/ui/shared/models/worker_services.py",
    "ui/shared/code_generation.py": "src/ui/shared/widgets/code_generation.py",
    "ui/shared/combo.py": "src/ui/shared/widgets/combo.py",
    "ui/shared/guards.py": "src/ui/shared/widgets/guards.py",
    "core/services/access/authorization.py": "src/core/platform/access/authorization.py",
    "core/services/access/domain.py": "src/core/platform/access/domain/access_scope.py",
    "core/services/access/policies.py": "src/core/platform/access/domain/feature_access.py",
    "core/services/access/service.py": "src/core/platform/access/application/access_control_service.py",
    "core/platform/access/service.py": "src/core/platform/access/application/access_control_service.py",
    "core/platform/audit/__init__.py": "src/core/platform/audit/__init__.py",
    "core/platform/audit/domain.py": "src/core/platform/audit/domain/__init__.py",
    "core/platform/audit/helpers.py": "src/core/platform/audit/helpers.py",
    "core/platform/audit/service.py": "src/core/platform/audit/application/audit_service.py",
    "core/services/approval/domain.py": "src/core/platform/approval/domain/__init__.py",
    "core/services/approval/policy.py": "src/core/platform/approval/policy.py",
    "core/services/approval/service.py": "src/core/platform/approval/application/approval_service.py",
    "core/services/auth/query.py": "src/core/platform/auth/application/auth_query.py",
    "core/services/auth/service.py": "src/core/platform/auth/application/auth_service.py",
    "core/services/auth/validation.py": "src/core/platform/auth/application/auth_validation.py",
    "core/platform/approval/__init__.py": "src/core/platform/approval/__init__.py",
    "core/platform/approval/domain.py": "src/core/platform/approval/domain/__init__.py",
    "core/platform/approval/policy.py": "src/core/platform/approval/policy.py",
    "core/platform/approval/service.py": "src/core/platform/approval/application/approval_service.py",
    "core/platform/documents/__init__.py": "src/core/platform/documents/__init__.py",
    "core/platform/documents/domain.py": "src/core/platform/documents/domain/__init__.py",
    "core/platform/documents/interfaces.py": "src/core/platform/documents/contracts.py",
    "core/platform/documents/integration_service.py": "src/core/platform/documents/application/document_integration_service.py",
    "core/platform/documents/service.py": "src/core/platform/documents/application/document_service.py",
    "core/platform/documents/support.py": "src/core/platform/documents/support.py",
    "core/platform/org/__init__.py": "src/core/platform/org/__init__.py",
    "core/platform/org/domain.py": "src/core/platform/org/domain/__init__.py",
    "core/platform/org/interfaces.py": "src/core/platform/org/contracts.py",
    "core/platform/org/service.py": "src/core/platform/org/__init__.py",
    "core/platform/org/organization_service.py": "src/core/platform/org/application/organization_service.py",
    "core/platform/org/site_service.py": "src/core/platform/org/application/site_service.py",
    "core/platform/org/department_service.py": "src/core/platform/org/application/department_service.py",
    "core/platform/org/employee_service.py": "src/core/platform/org/application/employee_service.py",
    "core/platform/org/employee_support.py": "src/core/platform/org/application/employee_support.py",
    "core/platform/org/support.py": "src/core/platform/org/support.py",
    "core/platform/org/access_policy.py": "src/core/platform/org/access_policy.py",
    "core/platform/party/__init__.py": "src/core/platform/party/__init__.py",
    "core/platform/party/domain.py": "src/core/platform/party/domain/party.py",
    "core/platform/party/interfaces.py": "src/core/platform/party/contracts.py",
    "core/platform/party/service.py": "src/core/platform/party/application/party_service.py",
    "core/platform/modules/__init__.py": "src/core/platform/modules/__init__.py",
    "core/platform/modules/authorization.py": "src/core/platform/modules/application/authorization.py",
    "core/platform/modules/catalog_context.py": "src/core/platform/modules/application/module_catalog_context.py",
    "core/platform/modules/catalog_models.py": "src/core/platform/modules/domain/__init__.py",
    "core/platform/modules/catalog_mutation.py": "src/core/platform/modules/application/module_catalog_mutation.py",
    "core/platform/modules/catalog_query.py": "src/core/platform/modules/application/module_catalog_query.py",
    "core/platform/modules/contracts.py": "src/core/platform/modules/contracts.py",
    "core/platform/modules/defaults.py": "src/core/platform/modules/domain/defaults.py",
    "core/platform/modules/guard.py": "src/core/platform/modules/application/guard.py",
    "core/platform/modules/module_codes.py": "src/core/platform/modules/domain/module_codes.py",
    "core/platform/modules/repository.py": "src/core/platform/modules/contracts.py",
    "core/platform/modules/service.py": "src/core/platform/modules/application/module_catalog_service.py",
    "core/platform/notifications/__init__.py": "src/core/platform/notifications/__init__.py",
    "core/platform/notifications/domain_events.py": "src/core/platform/notifications/domain_events.py",
    "core/platform/notifications/signal.py": "src/core/platform/notifications/signal.py",
    "infra/platform/service_registration/platform_bundle.py": "src/infra/composition/platform_registry.py",
    "infra/platform/service_registration/project_management_bundle.py": "src/infra/composition/project_registry.py",
    "infra/platform/service_registration/inventory_procurement_bundle.py": "src/infra/composition/inventory_registry.py",
    "infra/platform/service_registration/maintenance_management_bundle.py": "src/infra/composition/maintenance_registry.py",
    "infra/services.py": "src/infra/composition/app_container.py",
    "ui/main_window.py": "src/ui/shell/main_window.py",
    "ui/admin/audit_tab.py": "src/ui/platform/workspaces/control/audit/tab.py",
}

PATH_REWRITE_PREFIXES = (
    ("ui/access/", "src/ui/platform/workspaces/admin/access/"),
    ("ui/admin/", "src/ui/platform/workspaces/admin/"),
    ("ui/auth/", "src/ui/shared/dialogs/"),
    ("ui/calendar/", "ui/modules/project_management/calendar/"),
    ("ui/collaboration/", "ui/modules/project_management/collaboration/"),
    ("ui/cost/", "ui/modules/project_management/cost/"),
    ("ui/dashboard/", "ui/modules/project_management/dashboard/"),
    ("ui/governance/", "ui/modules/project_management/governance/"),
    ("ui/portfolio/", "ui/modules/project_management/portfolio/"),
    ("ui/project/", "ui/modules/project_management/project/"),
    ("ui/register/", "ui/modules/project_management/register/"),
    ("ui/report/", "ui/modules/project_management/report/"),
    ("ui/resource/", "ui/modules/project_management/resource/"),
    ("ui/control/", "src/ui/platform/workspaces/control/"),
    ("ui/settings/", "src/ui/platform/settings/"),
    ("ui/platform/settings/", "src/ui/platform/settings/"),
    ("ui/shared/", "src/ui/shared/"),
    ("ui/platform/shell/", "src/ui/shell/"),
    ("ui/shell/", "src/ui/shell/"),
    ("ui/styles/", "src/ui/shared/formatting/"),
    ("ui/support/", "src/ui/platform/workspaces/admin/support/"),
    ("ui/task/", "ui/modules/project_management/task/"),
    ("ui/timesheet/", "ui/modules/project_management/timesheet/"),
    ("core/domain/", "core/modules/project_management/domain/"),
    ("core/events/", "core/platform/notifications/"),
    ("core/reporting/", "core/modules/project_management/reporting/"),
    ("core/services/access/", "src/core/platform/access/"),
    ("core/services/approval/", "src/core/platform/approval/"),
    ("core/services/audit/", "core/platform/audit/"),
    ("core/services/baseline/", "core/modules/project_management/services/baseline/"),
    ("core/services/calendar/", "core/modules/project_management/services/calendar/"),
    ("core/services/collaboration/", "core/modules/project_management/services/collaboration/"),
    ("core/services/common/", "core/modules/project_management/services/common/"),
    ("core/services/cost/", "core/modules/project_management/services/cost/"),
    ("core/services/dashboard/", "core/modules/project_management/services/dashboard/"),
    ("core/services/finance/", "core/modules/project_management/services/finance/"),
    ("core/services/import_service/", "core/modules/project_management/services/import_service/"),
    ("core/services/portfolio/", "core/modules/project_management/services/portfolio/"),
    ("core/services/project/", "core/modules/project_management/services/project/"),
    ("core/services/register/", "core/modules/project_management/services/register/"),
    ("core/services/reporting/", "core/modules/project_management/services/reporting/"),
    ("core/services/resource/", "core/modules/project_management/services/resource/"),
    ("core/services/scheduling/", "core/modules/project_management/services/scheduling/"),
    ("core/services/task/", "core/modules/project_management/services/task/"),
    ("core/services/timesheet/", "core/modules/project_management/services/timesheet/"),
    ("core/services/work_calendar/", "core/modules/project_management/services/work_calendar/"),
    ("infra/db/access/", "src/infra/persistence/db/platform/access/"),
    ("infra/db/approval/", "src/infra/persistence/db/platform/approval/"),
    ("infra/db/audit/", "src/infra/persistence/db/platform/audit/"),
    ("infra/db/auth/", "src/infra/persistence/db/platform/auth/"),
    ("infra/db/documents/", "src/infra/persistence/db/platform/documents/"),
    ("infra/db/modules/", "src/infra/persistence/db/platform/modules/"),
    ("infra/db/org/", "src/infra/persistence/db/platform/org/"),
    ("infra/db/party/", "src/infra/persistence/db/platform/party/"),
    ("infra/db/runtime_tracking/", "src/infra/persistence/db/platform/runtime_tracking/"),
    ("infra/db/time/", "src/infra/persistence/db/platform/time/"),
    ("infra/db/baseline/", "infra/modules/project_management/db/baseline/"),
    ("infra/db/collaboration/", "infra/modules/project_management/db/collaboration/"),
    ("infra/db/cost_calendar/", "infra/modules/project_management/db/cost_calendar/"),
    ("infra/db/portfolio/", "infra/modules/project_management/db/portfolio/"),
    ("infra/db/project/", "infra/modules/project_management/db/project/"),
    ("infra/db/register/", "infra/modules/project_management/db/register/"),
    ("infra/db/resource/", "infra/modules/project_management/db/resource/"),
    ("infra/db/task/", "infra/modules/project_management/db/task/"),
    ("infra/db/timesheet/", "infra/modules/project_management/db/timesheet/"),
    ("infra/db/repositories_approval.py", "src/infra/persistence/db/platform/approval/repository.py"),
    ("infra/db/repositories_audit.py", "src/infra/persistence/db/platform/audit/repository.py"),
    ("infra/db/repositories_auth.py", "src/infra/persistence/db/platform/auth/repository.py"),
    ("infra/db/repositories_baseline.py", "infra/modules/project_management/db/baseline/repository.py"),
    ("infra/db/repositories_cost_calendar.py", "infra/modules/project_management/db/cost_calendar/repository.py"),
    ("infra/db/repositories_project.py", "infra/modules/project_management/db/project/repository.py"),
    ("infra/db/repositories_register.py", "infra/modules/project_management/db/register/repository.py"),
    ("infra/db/repositories_resource.py", "infra/modules/project_management/db/resource/repository.py"),
    ("infra/db/repositories_task.py", "infra/modules/project_management/db/task/repository.py"),
    ("infra/db/repositories_timesheet.py", "src/infra/persistence/db/platform/time/repository.py"),
)


def resolve_repo_path(path: Path) -> Path:
    try:
        relative = path.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path
    if relative in PATH_REWRITE_EXACT:
        return REPO_ROOT / PATH_REWRITE_EXACT[relative]
    for old_prefix, new_prefix in PATH_REWRITE_PREFIXES:
        trimmed = old_prefix.rstrip("/")
        if relative == trimmed:
            return REPO_ROOT / new_prefix.rstrip("/")
        if relative.startswith(old_prefix):
            return REPO_ROOT / (new_prefix + relative[len(old_prefix) :])
    return path


__all__ = [
    "PATH_REWRITE_EXACT",
    "PATH_REWRITE_PREFIXES",
    "REPO_ROOT",
    "resolve_repo_path",
]
