# core/interfaces.py
from __future__ import annotations
from abc import ABC, abstractmethod
from typing import List, Optional
from .models import (
    Project,
    Task,
    Resource,
    TaskAssignment,
    TaskDependency,
    CostItem,
    CalendarEvent,
    WorkingCalendar,
    Holiday,
    ProjectBaseline,
    BaselineTask,
    ProjectResource,
)


class ProjectRepository(ABC):
    @abstractmethod
    def add(self, project: Project) -> None: ...
    @abstractmethod
    def update(self, project: Project) -> None: ...
    @abstractmethod
    def delete(self, project_id: str) -> None: ...
    @abstractmethod
    def get(self, project_id: str) -> Optional[Project]: ...
    @abstractmethod
    def list_all(self) -> List[Project]: ...

class ProjectResourceRepository(ABC):
    def add(self, pr: ProjectResource) -> None: ...
    def get(self, pr_id: str) -> Optional[ProjectResource]: ...
    def list_by_project(self, project_id: str) -> List[ProjectResource]: ...
    def get_for_project(self, project_id: str, resource_id: str) -> Optional[ProjectResource]: ...
    def delete(self, pr_id: str) -> None: ...
    def delete_by_resource(self, res_id: str) -> None: ...
    def update(self, pr_id: ProjectResource) -> None: ...
    
class TaskRepository(ABC):
    @abstractmethod
    def add(self, task: Task) -> None: ...
    @abstractmethod
    def update(self, task: Task) -> None: ...
    @abstractmethod
    def delete(self, task_id: str) -> None: ...
    @abstractmethod
    def get(self, task_id: str) -> Optional[Task]: ...
    @abstractmethod
    def list_by_project(self, project_id: str) -> List[Task]: ...


class ResourceRepository(ABC):
    @abstractmethod
    def add(self, resource: Resource) -> None: ...
    @abstractmethod
    def update(self, resource: Resource) -> None: ...
    @abstractmethod
    def delete(self, resource_id: str) -> None: ...
    @abstractmethod
    def get(self, resource_id: str) -> Optional[Resource]: ...
    @abstractmethod
    def list_all(self) -> List[Resource]: ...


class AssignmentRepository(ABC):
    @abstractmethod
    def add(self, assignment: TaskAssignment) -> None: ...
    @abstractmethod
    def get(self, assignment_id: str) -> Optional[TaskAssignment]: ...
    @abstractmethod
    def list_by_task(self, task_id: str) -> List[TaskAssignment]: ...
    @abstractmethod
    def list_by_resource(self, resource_id: str) -> List[TaskAssignment]: ...
    @abstractmethod
    def update(self, assignment: TaskAssignment) -> None: ...
    @abstractmethod
    def delete(self, assignment_id: str) -> None: ...
    @abstractmethod
    def delete_by_task(self, task_id: str) -> None: ...
    @abstractmethod
    def list_by_assignment(self, task_id: str) -> List[TaskAssignment]: ...
    @abstractmethod
    def list_by_tasks(self, task_ids: List[str]) -> List[TaskAssignment]: ...


class DependencyRepository(ABC):
    @abstractmethod
    def add(self, dependency: TaskDependency) -> None: ...
    @abstractmethod
    def get(self, dependency_id: str) -> Optional[TaskDependency]: ...
    @abstractmethod
    def list_by_project(self, project_id: str) -> List[TaskDependency]: ...
    @abstractmethod
    def delete(self, dependency_id: str) -> None: ...
    @abstractmethod
    def delete_for_task(self, task_id: str) -> None: ...
    @abstractmethod
    def list_by_task(self, task_id: str) -> List[TaskDependency]: ...
    

class CostRepository(ABC):
    @abstractmethod
    def add(self, cost_item: CostItem) -> None: ...
    @abstractmethod
    def update(self, cost_item: CostItem) -> None: ...
    @abstractmethod
    def delete(self, cost_id: str) -> None: ...
    @abstractmethod
    def list_by_project(self, project_id: str) -> List[CostItem]: ...
    @abstractmethod
    def delete_by_project(self, project_id: str) -> None: ...
    @abstractmethod
    def get(self, cost_id: str) -> Optional[CostItem]: ...

class CalendarEventRepository(ABC):
    @abstractmethod
    def add(self, event: CalendarEvent) -> None: ...
    @abstractmethod
    def update(self, event: CalendarEvent) -> None: ...
    @abstractmethod
    def delete(self, event_id: str) -> None: ...
    @abstractmethod
    def get(self, event_id: str) -> Optional[CalendarEvent]: ...
    @abstractmethod
    def list_for_project(self, project_id: str) -> List[CalendarEvent]: ...
    @abstractmethod
    def list_range(self, start_date, end_date) -> List[CalendarEvent]: ...
    @abstractmethod
    def delete_for_task(self, task_id: str) -> None: ...
    @abstractmethod
    def delete_for_project(self, project_id: str) -> None: ...
    

class WorkingCalendarRepository(ABC):
    @abstractmethod
    def get(self, calendar_id: str) -> Optional[WorkingCalendar]: ...
    @abstractmethod
    def get_default(self) -> Optional[WorkingCalendar]: ...
    @abstractmethod
    def upsert(self, calendar: WorkingCalendar) -> None: ...
    @abstractmethod
    def list_holidays(self, calendar_id: str) -> List[Holiday]: ...
    @abstractmethod
    def add_holiday(self, holiday: Holiday) -> None: ...
    @abstractmethod
    def delete_holiday(self, holiday_id: str) -> None: ...
    
class BaselineRepository:
    def add_baseline(self, b: ProjectBaseline) -> ProjectBaseline: ...
    def get_baseline(self, baseline_id: str) -> Optional[ProjectBaseline]: ...
    def get_latest_for_project(self, project_id: str) -> Optional[ProjectBaseline]: ...
    def list_for_project(self, project_id: str) -> List[ProjectBaseline]: ...
    def delete_baseline(self, baseline_id: str) -> None: ...

    def add_baseline_tasks(self, tasks: List[BaselineTask]) -> None: ...
    def list_tasks(self, baseline_id: str) -> List[BaselineTask]: ...
    def delete_tasks(self, baseline_id: str) -> None: ...
