from __future__ import annotations

from core.modules.maintenance_management.domain import (
    MaintenanceAsset,
    MaintenanceAssetComponent,
    MaintenanceLocation,
    MaintenanceWorkOrderMaterialRequirement,
    MaintenanceSystem,
    MaintenanceWorkOrder,
    MaintenanceWorkOrderTask,
    MaintenanceWorkOrderTaskStep,
    MaintenanceWorkRequest,
)
from infra.platform.db.maintenance_models import (
    MaintenanceAssetComponentORM,
    MaintenanceAssetORM,
    MaintenanceLocationORM,
    MaintenanceSystemORM,
    MaintenanceWorkOrderMaterialRequirementORM,
    MaintenanceWorkOrderORM,
    MaintenanceWorkOrderTaskORM,
    MaintenanceWorkOrderTaskStepORM,
    MaintenanceWorkRequestORM,
)


def maintenance_location_to_orm(location: MaintenanceLocation) -> MaintenanceLocationORM:
    return MaintenanceLocationORM(
        id=location.id,
        organization_id=location.organization_id,
        site_id=location.site_id,
        location_code=location.location_code,
        name=location.name,
        description=location.description or None,
        parent_location_id=location.parent_location_id,
        location_type=location.location_type or None,
        criticality=location.criticality,
        status=location.status,
        is_active=location.is_active,
        created_at=location.created_at,
        updated_at=location.updated_at,
        notes=location.notes or None,
        version=getattr(location, "version", 1),
    )


def maintenance_location_from_orm(obj: MaintenanceLocationORM) -> MaintenanceLocation:
    return MaintenanceLocation(
        id=obj.id,
        organization_id=obj.organization_id,
        site_id=obj.site_id,
        location_code=obj.location_code,
        name=obj.name,
        description=obj.description or "",
        parent_location_id=obj.parent_location_id,
        location_type=obj.location_type or "",
        criticality=obj.criticality,
        status=obj.status,
        is_active=obj.is_active,
        created_at=obj.created_at,
        updated_at=obj.updated_at,
        notes=obj.notes or "",
        version=getattr(obj, "version", 1),
    )


def maintenance_system_to_orm(system: MaintenanceSystem) -> MaintenanceSystemORM:
    return MaintenanceSystemORM(
        id=system.id,
        organization_id=system.organization_id,
        site_id=system.site_id,
        system_code=system.system_code,
        name=system.name,
        location_id=system.location_id,
        description=system.description or None,
        parent_system_id=system.parent_system_id,
        system_type=system.system_type or None,
        criticality=system.criticality,
        status=system.status,
        is_active=system.is_active,
        created_at=system.created_at,
        updated_at=system.updated_at,
        notes=system.notes or None,
        version=getattr(system, "version", 1),
    )


def maintenance_system_from_orm(obj: MaintenanceSystemORM) -> MaintenanceSystem:
    return MaintenanceSystem(
        id=obj.id,
        organization_id=obj.organization_id,
        site_id=obj.site_id,
        system_code=obj.system_code,
        name=obj.name,
        location_id=obj.location_id,
        description=obj.description or "",
        parent_system_id=obj.parent_system_id,
        system_type=obj.system_type or "",
        criticality=obj.criticality,
        status=obj.status,
        is_active=obj.is_active,
        created_at=obj.created_at,
        updated_at=obj.updated_at,
        notes=obj.notes or "",
        version=getattr(obj, "version", 1),
    )


def maintenance_asset_to_orm(asset: MaintenanceAsset) -> MaintenanceAssetORM:
    return MaintenanceAssetORM(
        id=asset.id,
        organization_id=asset.organization_id,
        site_id=asset.site_id,
        location_id=asset.location_id,
        asset_code=asset.asset_code,
        name=asset.name,
        system_id=asset.system_id,
        description=asset.description or None,
        parent_asset_id=asset.parent_asset_id,
        asset_type=asset.asset_type or None,
        asset_category=asset.asset_category or None,
        status=asset.status,
        criticality=asset.criticality,
        manufacturer_party_id=asset.manufacturer_party_id,
        supplier_party_id=asset.supplier_party_id,
        model_number=asset.model_number or None,
        serial_number=asset.serial_number or None,
        barcode=asset.barcode or None,
        install_date=asset.install_date,
        commission_date=asset.commission_date,
        warranty_start=asset.warranty_start,
        warranty_end=asset.warranty_end,
        expected_life_years=asset.expected_life_years,
        replacement_cost=asset.replacement_cost,
        maintenance_strategy=asset.maintenance_strategy or None,
        service_level=asset.service_level or None,
        requires_shutdown_for_major_work=asset.requires_shutdown_for_major_work,
        is_active=asset.is_active,
        created_at=asset.created_at,
        updated_at=asset.updated_at,
        notes=asset.notes or None,
        version=getattr(asset, "version", 1),
    )


def maintenance_asset_from_orm(obj: MaintenanceAssetORM) -> MaintenanceAsset:
    return MaintenanceAsset(
        id=obj.id,
        organization_id=obj.organization_id,
        site_id=obj.site_id,
        location_id=obj.location_id,
        asset_code=obj.asset_code,
        name=obj.name,
        system_id=obj.system_id,
        description=obj.description or "",
        parent_asset_id=obj.parent_asset_id,
        asset_type=obj.asset_type or "",
        asset_category=obj.asset_category or "",
        status=obj.status,
        criticality=obj.criticality,
        manufacturer_party_id=obj.manufacturer_party_id,
        supplier_party_id=obj.supplier_party_id,
        model_number=obj.model_number or "",
        serial_number=obj.serial_number or "",
        barcode=obj.barcode or "",
        install_date=obj.install_date,
        commission_date=obj.commission_date,
        warranty_start=obj.warranty_start,
        warranty_end=obj.warranty_end,
        expected_life_years=obj.expected_life_years,
        replacement_cost=obj.replacement_cost,
        maintenance_strategy=obj.maintenance_strategy or "",
        service_level=obj.service_level or "",
        requires_shutdown_for_major_work=obj.requires_shutdown_for_major_work,
        is_active=obj.is_active,
        created_at=obj.created_at,
        updated_at=obj.updated_at,
        notes=obj.notes or "",
        version=getattr(obj, "version", 1),
    )


def maintenance_asset_component_to_orm(component: MaintenanceAssetComponent) -> MaintenanceAssetComponentORM:
    return MaintenanceAssetComponentORM(
        id=component.id,
        organization_id=component.organization_id,
        asset_id=component.asset_id,
        component_code=component.component_code,
        name=component.name,
        description=component.description or None,
        parent_component_id=component.parent_component_id,
        component_type=component.component_type or None,
        status=component.status,
        manufacturer_party_id=component.manufacturer_party_id,
        supplier_party_id=component.supplier_party_id,
        manufacturer_part_number=component.manufacturer_part_number or None,
        supplier_part_number=component.supplier_part_number or None,
        model_number=component.model_number or None,
        serial_number=component.serial_number or None,
        install_date=component.install_date,
        warranty_end=component.warranty_end,
        expected_life_hours=component.expected_life_hours,
        expected_life_cycles=component.expected_life_cycles,
        is_critical_component=component.is_critical_component,
        is_active=component.is_active,
        created_at=component.created_at,
        updated_at=component.updated_at,
        notes=component.notes or None,
        version=getattr(component, "version", 1),
    )


def maintenance_asset_component_from_orm(obj: MaintenanceAssetComponentORM) -> MaintenanceAssetComponent:
    return MaintenanceAssetComponent(
        id=obj.id,
        organization_id=obj.organization_id,
        asset_id=obj.asset_id,
        component_code=obj.component_code,
        name=obj.name,
        description=obj.description or "",
        parent_component_id=obj.parent_component_id,
        component_type=obj.component_type or "",
        status=obj.status,
        manufacturer_party_id=obj.manufacturer_party_id,
        supplier_party_id=obj.supplier_party_id,
        manufacturer_part_number=obj.manufacturer_part_number or "",
        supplier_part_number=obj.supplier_part_number or "",
        model_number=obj.model_number or "",
        serial_number=obj.serial_number or "",
        install_date=obj.install_date,
        warranty_end=obj.warranty_end,
        expected_life_hours=obj.expected_life_hours,
        expected_life_cycles=obj.expected_life_cycles,
        is_critical_component=obj.is_critical_component,
        is_active=obj.is_active,
        created_at=obj.created_at,
        updated_at=obj.updated_at,
        notes=obj.notes or "",
        version=getattr(obj, "version", 1),
    )


def maintenance_work_request_to_orm(work_request: MaintenanceWorkRequest) -> MaintenanceWorkRequestORM:
    return MaintenanceWorkRequestORM(
        id=work_request.id,
        organization_id=work_request.organization_id,
        site_id=work_request.site_id,
        work_request_code=work_request.work_request_code,
        source_type=work_request.source_type,
        request_type=work_request.request_type,
        asset_id=work_request.asset_id,
        component_id=work_request.component_id,
        system_id=work_request.system_id,
        location_id=work_request.location_id,
        title=work_request.title,
        description=work_request.description,
        priority=work_request.priority,
        status=work_request.status,
        requested_at=work_request.requested_at,
        requested_by_user_id=work_request.requested_by_user_id,
        requested_by_name_snapshot=work_request.requested_by_name_snapshot,
        triaged_at=work_request.triaged_at,
        triaged_by_user_id=work_request.triaged_by_user_id,
        failure_symptom_code=work_request.failure_symptom_code,
        safety_risk_level=work_request.safety_risk_level,
        production_impact_level=work_request.production_impact_level,
        notes=work_request.notes,
        created_at=work_request.created_at,
        updated_at=work_request.updated_at,
        version=getattr(work_request, "version", 1),
    )


def maintenance_work_request_from_orm(obj: MaintenanceWorkRequestORM) -> MaintenanceWorkRequest:
    return MaintenanceWorkRequest(
        id=obj.id,
        organization_id=obj.organization_id,
        site_id=obj.site_id,
        work_request_code=obj.work_request_code,
        source_type=obj.source_type,
        request_type=obj.request_type,
        asset_id=obj.asset_id,
        component_id=obj.component_id,
        system_id=obj.system_id,
        location_id=obj.location_id,
        title=obj.title,
        description=obj.description,
        priority=obj.priority,
        status=obj.status,
        requested_at=obj.requested_at,
        requested_by_user_id=obj.requested_by_user_id,
        requested_by_name_snapshot=obj.requested_by_name_snapshot,
        triaged_at=obj.triaged_at,
        triaged_by_user_id=obj.triaged_by_user_id,
        failure_symptom_code=obj.failure_symptom_code,
        safety_risk_level=obj.safety_risk_level,
        production_impact_level=obj.production_impact_level,
        notes=obj.notes,
        created_at=obj.created_at,
        updated_at=obj.updated_at,
        version=getattr(obj, "version", 1),
    )


def maintenance_work_order_to_orm(work_order: MaintenanceWorkOrder) -> MaintenanceWorkOrderORM:
    return MaintenanceWorkOrderORM(
        id=work_order.id,
        organization_id=work_order.organization_id,
        site_id=work_order.site_id,
        work_order_code=work_order.work_order_code,
        work_order_type=work_order.work_order_type,
        source_type=work_order.source_type,
        source_id=work_order.source_id,
        asset_id=work_order.asset_id,
        component_id=work_order.component_id,
        system_id=work_order.system_id,
        location_id=work_order.location_id,
        title=work_order.title,
        description=work_order.description,
        priority=work_order.priority,
        status=work_order.status,
        requested_by_user_id=work_order.requested_by_user_id,
        planner_user_id=work_order.planner_user_id,
        supervisor_user_id=work_order.supervisor_user_id,
        assigned_team_id=work_order.assigned_team_id,
        assigned_employee_id=work_order.assigned_employee_id,
        planned_start=work_order.planned_start,
        planned_end=work_order.planned_end,
        actual_start=work_order.actual_start,
        actual_end=work_order.actual_end,
        requires_shutdown=work_order.requires_shutdown,
        permit_required=work_order.permit_required,
        approval_required=work_order.approval_required,
        failure_code=work_order.failure_code,
        root_cause_code=work_order.root_cause_code,
        downtime_minutes=work_order.downtime_minutes,
        parts_cost=work_order.parts_cost,
        labor_cost=work_order.labor_cost,
        vendor_party_id=work_order.vendor_party_id,
        is_preventive=work_order.is_preventive,
        is_emergency=work_order.is_emergency,
        closed_at=work_order.closed_at,
        closed_by_user_id=work_order.closed_by_user_id,
        notes=work_order.notes,
        created_at=work_order.created_at,
        updated_at=work_order.updated_at,
        version=getattr(work_order, "version", 1),
    )


def maintenance_work_order_from_orm(obj: MaintenanceWorkOrderORM) -> MaintenanceWorkOrder:
    return MaintenanceWorkOrder(
        id=obj.id,
        organization_id=obj.organization_id,
        site_id=obj.site_id,
        work_order_code=obj.work_order_code,
        work_order_type=obj.work_order_type,
        source_type=obj.source_type,
        source_id=obj.source_id,
        asset_id=obj.asset_id,
        component_id=obj.component_id,
        system_id=obj.system_id,
        location_id=obj.location_id,
        title=obj.title,
        description=obj.description,
        priority=obj.priority,
        status=obj.status,
        requested_by_user_id=obj.requested_by_user_id,
        planner_user_id=obj.planner_user_id,
        supervisor_user_id=obj.supervisor_user_id,
        assigned_team_id=obj.assigned_team_id,
        assigned_employee_id=obj.assigned_employee_id,
        planned_start=obj.planned_start,
        planned_end=obj.planned_end,
        actual_start=obj.actual_start,
        actual_end=obj.actual_end,
        requires_shutdown=obj.requires_shutdown,
        permit_required=obj.permit_required,
        approval_required=obj.approval_required,
        failure_code=obj.failure_code,
        root_cause_code=obj.root_cause_code,
        downtime_minutes=obj.downtime_minutes,
        parts_cost=obj.parts_cost,
        labor_cost=obj.labor_cost,
        vendor_party_id=obj.vendor_party_id,
        is_preventive=obj.is_preventive,
        is_emergency=obj.is_emergency,
        closed_at=obj.closed_at,
        closed_by_user_id=obj.closed_by_user_id,
        notes=obj.notes,
        created_at=obj.created_at,
        updated_at=obj.updated_at,
        version=getattr(obj, "version", 1),
    )


def maintenance_work_order_task_to_orm(work_order_task: MaintenanceWorkOrderTask) -> MaintenanceWorkOrderTaskORM:
    return MaintenanceWorkOrderTaskORM(
        id=work_order_task.id,
        organization_id=work_order_task.organization_id,
        work_order_id=work_order_task.work_order_id,
        task_template_id=work_order_task.task_template_id,
        task_name=work_order_task.task_name,
        description=work_order_task.description,
        assigned_employee_id=work_order_task.assigned_employee_id,
        assigned_team_id=work_order_task.assigned_team_id,
        estimated_minutes=work_order_task.estimated_minutes,
        actual_minutes=work_order_task.actual_minutes,
        required_skill=work_order_task.required_skill,
        status=work_order_task.status,
        started_at=work_order_task.started_at,
        completed_at=work_order_task.completed_at,
        sequence_no=work_order_task.sequence_no,
        is_mandatory=work_order_task.is_mandatory,
        completion_rule=work_order_task.completion_rule,
        notes=work_order_task.notes,
        created_at=work_order_task.created_at,
        updated_at=work_order_task.updated_at,
        version=getattr(work_order_task, "version", 1),
    )


def maintenance_work_order_task_from_orm(obj: MaintenanceWorkOrderTaskORM) -> MaintenanceWorkOrderTask:
    return MaintenanceWorkOrderTask(
        id=obj.id,
        organization_id=obj.organization_id,
        work_order_id=obj.work_order_id,
        task_template_id=obj.task_template_id,
        task_name=obj.task_name,
        description=obj.description,
        assigned_employee_id=obj.assigned_employee_id,
        assigned_team_id=obj.assigned_team_id,
        estimated_minutes=obj.estimated_minutes,
        actual_minutes=obj.actual_minutes,
        required_skill=obj.required_skill,
        status=obj.status,
        started_at=obj.started_at,
        completed_at=obj.completed_at,
        sequence_no=obj.sequence_no,
        is_mandatory=obj.is_mandatory,
        completion_rule=obj.completion_rule,
        notes=obj.notes,
        created_at=obj.created_at,
        updated_at=obj.updated_at,
        version=getattr(obj, "version", 1),
    )


def maintenance_work_order_task_step_to_orm(
    work_order_task_step: MaintenanceWorkOrderTaskStep,
) -> MaintenanceWorkOrderTaskStepORM:
    return MaintenanceWorkOrderTaskStepORM(
        id=work_order_task_step.id,
        organization_id=work_order_task_step.organization_id,
        work_order_task_id=work_order_task_step.work_order_task_id,
        source_step_template_id=work_order_task_step.source_step_template_id,
        step_number=work_order_task_step.step_number,
        instruction=work_order_task_step.instruction,
        expected_result=work_order_task_step.expected_result,
        hint_level=work_order_task_step.hint_level,
        hint_text=work_order_task_step.hint_text,
        status=work_order_task_step.status,
        requires_confirmation=work_order_task_step.requires_confirmation,
        requires_measurement=work_order_task_step.requires_measurement,
        requires_photo=work_order_task_step.requires_photo,
        measurement_value=work_order_task_step.measurement_value,
        measurement_unit=work_order_task_step.measurement_unit,
        completed_by_user_id=work_order_task_step.completed_by_user_id,
        completed_at=work_order_task_step.completed_at,
        confirmed_by_user_id=work_order_task_step.confirmed_by_user_id,
        confirmed_at=work_order_task_step.confirmed_at,
        notes=work_order_task_step.notes,
        created_at=work_order_task_step.created_at,
        updated_at=work_order_task_step.updated_at,
        version=getattr(work_order_task_step, "version", 1),
    )


def maintenance_work_order_task_step_from_orm(
    obj: MaintenanceWorkOrderTaskStepORM,
) -> MaintenanceWorkOrderTaskStep:
    return MaintenanceWorkOrderTaskStep(
        id=obj.id,
        organization_id=obj.organization_id,
        work_order_task_id=obj.work_order_task_id,
        source_step_template_id=obj.source_step_template_id,
        step_number=obj.step_number,
        instruction=obj.instruction,
        expected_result=obj.expected_result,
        hint_level=obj.hint_level,
        hint_text=obj.hint_text,
        status=obj.status,
        requires_confirmation=obj.requires_confirmation,
        requires_measurement=obj.requires_measurement,
        requires_photo=obj.requires_photo,
        measurement_value=obj.measurement_value,
        measurement_unit=obj.measurement_unit,
        completed_by_user_id=obj.completed_by_user_id,
        completed_at=obj.completed_at,
        confirmed_by_user_id=obj.confirmed_by_user_id,
        confirmed_at=obj.confirmed_at,
        notes=obj.notes,
        created_at=obj.created_at,
        updated_at=obj.updated_at,
        version=getattr(obj, "version", 1),
    )


def maintenance_work_order_material_requirement_to_orm(
    material_requirement: MaintenanceWorkOrderMaterialRequirement,
) -> MaintenanceWorkOrderMaterialRequirementORM:
    return MaintenanceWorkOrderMaterialRequirementORM(
        id=material_requirement.id,
        organization_id=material_requirement.organization_id,
        work_order_id=material_requirement.work_order_id,
        stock_item_id=material_requirement.stock_item_id,
        description=material_requirement.description,
        required_qty=material_requirement.required_qty,
        issued_qty=material_requirement.issued_qty,
        required_uom=material_requirement.required_uom,
        is_stock_item=material_requirement.is_stock_item,
        preferred_storeroom_id=material_requirement.preferred_storeroom_id,
        procurement_status=material_requirement.procurement_status,
        last_availability_status=material_requirement.last_availability_status,
        last_missing_qty=material_requirement.last_missing_qty,
        linked_requisition_id=material_requirement.linked_requisition_id,
        notes=material_requirement.notes,
        created_at=material_requirement.created_at,
        updated_at=material_requirement.updated_at,
        version=getattr(material_requirement, "version", 1),
    )


def maintenance_work_order_material_requirement_from_orm(
    obj: MaintenanceWorkOrderMaterialRequirementORM,
) -> MaintenanceWorkOrderMaterialRequirement:
    return MaintenanceWorkOrderMaterialRequirement(
        id=obj.id,
        organization_id=obj.organization_id,
        work_order_id=obj.work_order_id,
        stock_item_id=obj.stock_item_id,
        description=obj.description,
        required_qty=obj.required_qty,
        issued_qty=obj.issued_qty,
        required_uom=obj.required_uom,
        is_stock_item=obj.is_stock_item,
        preferred_storeroom_id=obj.preferred_storeroom_id,
        procurement_status=obj.procurement_status,
        last_availability_status=obj.last_availability_status,
        last_missing_qty=obj.last_missing_qty,
        linked_requisition_id=obj.linked_requisition_id,
        notes=obj.notes,
        created_at=obj.created_at,
        updated_at=obj.updated_at,
        version=getattr(obj, "version", 1),
    )


__all__ = [
    "maintenance_asset_from_orm",
    "maintenance_asset_component_from_orm",
    "maintenance_asset_component_to_orm",
    "maintenance_asset_to_orm",
    "maintenance_location_from_orm",
    "maintenance_location_to_orm",
    "maintenance_work_order_material_requirement_from_orm",
    "maintenance_work_order_material_requirement_to_orm",
    "maintenance_system_from_orm",
    "maintenance_system_to_orm",
    "maintenance_work_order_from_orm",
    "maintenance_work_order_task_from_orm",
    "maintenance_work_order_task_step_from_orm",
    "maintenance_work_order_task_step_to_orm",
    "maintenance_work_order_task_to_orm",
    "maintenance_work_order_to_orm",
    "maintenance_work_request_from_orm",
    "maintenance_work_request_to_orm",
]
