"""Project code auto-generation + uniqueness (Phase A/B backend)."""

from __future__ import annotations

import pytest

from src.core.platform.common.exceptions import ValidationError


def test_create_project_autogenerates_code(services):
    ps = services["project_service"]
    project = ps.create_project("Plant Upgrade", "")
    assert project.code == "PRJ-PLAN-0001"


def test_create_project_accepts_manual_code(services):
    ps = services["project_service"]
    project = ps.create_project("Warehouse Retrofit", "", code="prj custom 7")
    # normalized: uppercased, unsafe runs -> '-'
    assert project.code == "PRJ-CUSTOM-7"


def test_create_project_rejects_duplicate_manual_code(services):
    ps = services["project_service"]
    ps.create_project("Alpha", "", code="PRJ-DUP-0001")
    with pytest.raises(ValidationError) as exc:
        ps.create_project("Beta", "", code="PRJ-DUP-0001")
    assert exc.value.code == "CODE_DUPLICATE"


def test_autogenerated_codes_are_unique_and_increment(services):
    ps = services["project_service"]
    # distinct names that share the same 4-char token -> incrementing sequence
    a = ps.create_project("Refinery One", "")
    b = ps.create_project("Refining Plant", "")
    assert a.code == "PRJ-REFI-0001"
    assert b.code == "PRJ-REFI-0002"


def test_project_code_round_trips_through_repository(services):
    ps = services["project_service"]
    created = ps.create_project("Bridge Works", "")
    reloaded = next(p for p in ps.list_projects() if p.id == created.id)
    assert reloaded.code == created.code == "PRJ-BRID-0001"
