from src.api.desktop.platform.models import (
    ApprovalDecisionCommand,
    ApprovalRequestDto,
    ApprovalStatus,
    WorkingCalendarDayDto,
    WorkingCalendarHolidayCreateCommand,
    WorkingCalendarHolidayDto,
    WorkingCalendarOptionDto,
    WorkingCalendarSnapshotDto,
    WorkingCalendarUpdateCommand,
    WorkingDayCalculationCommand,
    WorkingDayCalculationDto,
    DepartmentCreateCommand,
    DepartmentDto,
    DepartmentLocationReferenceDto,
    DepartmentUpdateCommand,
    DesktopApiError,
    DesktopApiResult,
    ScopeTargetDto,
    ScopeTypeChoiceDto,
    DocumentCreateCommand,
    DocumentDto,
    DocumentLinkCreateCommand,
    DocumentLinkDto,
    DocumentStructureCreateCommand,
    DocumentStructureDto,
    DocumentStructureUpdateCommand,
    DocumentUpdateCommand,
    EmployeeCreateCommand,
    EmployeeDto,
    EmployeeUpdateCommand,
    ApiKeyCredentialDto,
    ApiKeyIssueCommand,
    IssuedApiKeyDto,
    ServicePrincipalCreateCommand,
    ServicePrincipalDto,
    ModuleDto,
    ModuleEntitlementDto,
    ModuleStatePatchCommand,
    OrganizationDto,
    OrganizationProvisionCommand,
    OrganizationUpdateCommand,
    PartyCreateCommand,
    PartyDto,
    PartyUpdateCommand,
    PlatformCapabilityDto,
    PlatformRuntimeContextDto,
    RoleDto,
    ScopedAccessGrantAssignCommand,
    ScopedAccessGrantDto,
    ScopedAccessGrantRemoveCommand,
    SiteCreateCommand,
    SiteDto,
    SiteUpdateCommand,
    TenantInvitationDto,
    SupportBundleDto,
    SupportEventDto,
    SupportInstallLaunchDto,
    SupportPathsDto,
    SupportSettingsDto,
    SupportSettingsUpdateCommand,
    SupportUpdateStatusDto,
    UserCreateCommand,
    UserDto,
    UserPasswordResetCommand,
    UserUpdateCommand,
)
# PlatformCalendarDesktopApi removed — use EnterpriseCalendarDesktopApi instead
from src.api.desktop.platform.access import PlatformAccessDesktopApi
from src.core.platform.api.desktop.history.activity.activity import PlatformActivityDesktopApi
from src.core.platform.api.desktop.approval.approval import PlatformApprovalDesktopApi
from src.api.desktop.platform.document import PlatformDocumentDesktopApi
from src.api.desktop.platform.department import PlatformDepartmentDesktopApi
from src.api.desktop.platform.employee import PlatformEmployeeDesktopApi
from src.api.desktop.platform.identity import PlatformIdentityDesktopApi
from src.api.desktop.platform.party import PlatformPartyDesktopApi
from src.api.desktop.platform.runtime import PlatformRuntimeDesktopApi
from src.api.desktop.platform.site import PlatformSiteDesktopApi
from src.api.desktop.platform.support import PlatformSupportDesktopApi
from src.api.desktop.platform.tenant import PlatformTenantDesktopApi
from src.api.desktop.platform.user import PlatformUserDesktopApi

__all__ = [
    "ApiKeyCredentialDto",
    "ApiKeyIssueCommand",
    "ApprovalDecisionCommand",
    "ApprovalRequestDto",
    "ApprovalStatus",
    "WorkingCalendarDayDto",
    "WorkingCalendarHolidayCreateCommand",
    "WorkingCalendarHolidayDto",
    "WorkingCalendarOptionDto",
    "WorkingCalendarSnapshotDto",
    "WorkingCalendarUpdateCommand",
    "WorkingDayCalculationCommand",
    "WorkingDayCalculationDto",
    "DepartmentCreateCommand",
    "DepartmentDto",
    "DepartmentLocationReferenceDto",
    "DepartmentUpdateCommand",
    "DesktopApiError",
    "DesktopApiResult",
    "ScopeTargetDto",
    "ScopeTypeChoiceDto",
    "DocumentCreateCommand",
    "DocumentDto",
    "DocumentLinkCreateCommand",
    "DocumentLinkDto",
    "DocumentStructureCreateCommand",
    "DocumentStructureDto",
    "DocumentStructureUpdateCommand",
    "DocumentUpdateCommand",
    "EmployeeCreateCommand",
    "EmployeeDto",
    "EmployeeUpdateCommand",
    "IssuedApiKeyDto",
    "ModuleDto",
    "ModuleEntitlementDto",
    "ModuleStatePatchCommand",
    "OrganizationDto",
    "OrganizationProvisionCommand",
    "OrganizationUpdateCommand",
    "PartyCreateCommand",
    "PartyDto",
    "PartyUpdateCommand",
    "PlatformCapabilityDto",
    "PlatformAccessDesktopApi",
    "PlatformActivityDesktopApi",
    "PlatformApprovalDesktopApi",
    # "PlatformCalendarDesktopApi",  # removed — use EnterpriseCalendarDesktopApi
    "PlatformDocumentDesktopApi",
    "PlatformPartyDesktopApi",
    "PlatformRuntimeContextDto",
    "PlatformDepartmentDesktopApi",
    "PlatformEmployeeDesktopApi",
    "PlatformIdentityDesktopApi",
    "PlatformRuntimeDesktopApi",
    "PlatformSiteDesktopApi",
    "PlatformTenantDesktopApi",
    "PlatformUserDesktopApi",
    "RoleDto",
    "ScopedAccessGrantAssignCommand",
    "ScopedAccessGrantDto",
    "ScopedAccessGrantRemoveCommand",
    "SiteCreateCommand",
    "SiteDto",
    "SiteUpdateCommand",
    "ServicePrincipalCreateCommand",
    "ServicePrincipalDto",
    "TenantInvitationDto",
    "SupportBundleDto",
    "SupportEventDto",
    "SupportInstallLaunchDto",
    "SupportPathsDto",
    "SupportSettingsDto",
    "SupportSettingsUpdateCommand",
    "SupportUpdateStatusDto",
    "UserCreateCommand",
    "UserDto",
    "UserPasswordResetCommand",
    "PlatformSupportDesktopApi",
    "UserUpdateCommand",
]
